# Generated by Django 4.2.1 on 2023-06-25 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_customer_phone_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='user_profile',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='employeeassistant',
            old_name='user_profile',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='technician',
            old_name='user_profile',
            new_name='user',
        ),
    ]
