# Generated by Django 4.2.1 on 2023-06-25 18:53

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0003_alter_customer_user_profile_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('IN', 'Installation'), ('MA', 'Maintenance'), ('RE', 'Repair')], max_length=2)),
                ('unit_price', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ServiceOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('SC', 'Scheduled'), ('IP', 'In progress'), ('CO', 'Completed')], max_length=2)),
                ('scheduled_time', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.customer')),
                ('technician', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.technician')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='services.service')),
                ('service_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.serviceorder')),
            ],
        ),
    ]
